# Generated by Django 3.1.7 on 2021-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210401_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default='default_text', max_length=255),
            preserve_default=False,
        ),
    ]
